name: fluent_ui_utils
description: Collection of Widgets and helpful Methods that every developer needs.
version: 1.0.2
#homepage: https://iTechQua.github.io
repository: https://github.com/iTechQua/fluent_ui_utils
issue_tracker: https://github.com/iTechQua/fluent_ui_utils/issues
funding:
  - https://www.github.com/sponsors/iTechQua

environment:
  sdk: ^3.0.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

  fluent_ui: ^4.9.2
  itq_utils: ^2.0.2
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  clay_containers: ^0.3.4
  syncfusion_flutter_pdfviewer: ^27.2.4
  syncfusion_flutter_core: ^27.2.2
  syncfusion_flutter_xlsio: ^27.1.57
  syncfusion_flutter_datagrid: ^27.1.57
  universal_html: ^2.2.4
  pdf: ^3.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.fluent_ui_utils
        pluginClass: FluentUiUtilsPlugin
      ios:
        pluginClass: FluentUiUtilsPlugin
      linux:
        pluginClass: FluentUiUtilsPlugin
      macos:
        pluginClass: FluentUiUtilsPlugin
      windows:
        pluginClass: FluentUiUtilsPluginCApi
      web:
        pluginClass: FluentUiUtilsWeb
        fileName: fluent_ui_utils_web.dart
